# Kubernetes ServiceAccount configurations for Task Management System
# Version: v1.27+
# Purpose: Define service identities with enhanced security measures and strict access controls

---
# Backend Service Account for microservices
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service
  namespace: task-management
  labels:
    app.kubernetes.io/name: backend-service
    app.kubernetes.io/part-of: task-management
    security.kubernetes.io/critical: "true"
  annotations:
    # Enhanced security controls
    kubernetes.io/enforce-mountable-secrets: "true"
    security.kubernetes.io/token-rotation: "enabled"
    security.kubernetes.io/namespace-isolation: "strict"
    security.kubernetes.io/audit-level: "high"
    # Service binding and access control
    security.kubernetes.io/rbac-group: "backend"
    security.kubernetes.io/psp-profile: "restricted"
    # Documentation
    description: "Service account for backend microservices with enhanced security controls"
    security.kubernetes.io/last-updated: "2024-01-01"
automountServiceAccountToken: true
---
# Monitoring Service Account for observability tools
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-service
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring-service
    app.kubernetes.io/part-of: task-management
    security.kubernetes.io/critical: "true"
  annotations:
    # Enhanced security controls
    kubernetes.io/enforce-mountable-secrets: "true"
    security.kubernetes.io/token-rotation: "enabled"
    security.kubernetes.io/metrics-scope: "limited"
    security.kubernetes.io/audit-level: "high"
    # Service binding and access control
    security.kubernetes.io/rbac-group: "monitoring"
    security.kubernetes.io/psp-profile: "monitoring"
    # Documentation
    description: "Service account for monitoring tools with restricted permissions"
    security.kubernetes.io/last-updated: "2024-01-01"
automountServiceAccountToken: true
---
# Cache Service Account for Redis operations
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache-service
  namespace: task-management
  labels:
    app.kubernetes.io/name: cache-service
    app.kubernetes.io/part-of: task-management
    security.kubernetes.io/critical: "true"
  annotations:
    # Enhanced security controls
    kubernetes.io/enforce-mountable-secrets: "true"
    security.kubernetes.io/token-rotation: "enabled"
    security.kubernetes.io/cache-access: "restricted"
    security.kubernetes.io/audit-level: "high"
    # Service binding and access control
    security.kubernetes.io/rbac-group: "cache"
    security.kubernetes.io/psp-profile: "cache"
    # Documentation
    description: "Service account for cache services with minimal required permissions"
    security.kubernetes.io/last-updated: "2024-01-01"
automountServiceAccountToken: true