# Kubernetes ConfigMap for Backend Service Configuration
# Version: 1.0.0
# Kubernetes API Version: v1 (1.27+)
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: task-management
  labels:
    app: backend
    environment: production
    version: 1.0.0
    managed-by: kubernetes
  annotations:
    description: "Production configuration for Task Management System backend service"
    lastUpdated: "2024-01-01"
data:
  # Core Application Settings
  NODE_ENV: "production"
  PORT: "3000"
  API_PREFIX: "/api/v1"
  API_RATE_LIMIT: "100"  # Requests per minute
  API_TIMEOUT: "30000"   # 30 seconds in milliseconds

  # Database Configuration (PostgreSQL)
  DATABASE_HOST: "postgres-rds.task-management.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "taskmanagement"
  DATABASE_USER: "app_user"
  DATABASE_SSL: "true"
  DATABASE_POOL_MIN: "5"
  DATABASE_POOL_MAX: "20"
  DATABASE_IDLE_TIMEOUT: "10000"  # 10 seconds in milliseconds

  # Redis Cache Configuration
  REDIS_HOST: "redis-cache.task-management.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_TTL: "3600"              # 1 hour in seconds
  REDIS_CLUSTER_MODE: "true"
  REDIS_KEY_PREFIX: "tms:"       # Task Management System prefix
  REDIS_MAX_RETRIES: "3"
  REDIS_RETRY_INTERVAL: "1000"   # 1 second in milliseconds

  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"             # JSON format for better log aggregation
  LOG_MAX_SIZE: "10m"           # Maximum log file size
  LOG_MAX_FILES: "7"            # Number of log files to retain

  # Metrics and Monitoring
  METRICS_ENABLED: "true"
  METRICS_PATH: "/metrics"

  # Authentication and Security
  JWT_EXPIRES_IN: "1h"          # JWT token expiration
  REFRESH_TOKEN_EXPIRES_IN: "7d" # Refresh token expiration
  SSO_PROVIDER: "Auth0"
  SSO_DOMAIN: "taskmanagement.auth0.com"

  # CORS Configuration
  CORS_ORIGIN: "https://taskmanagement.com"
  CORS_METHODS: "GET,POST,PUT,DELETE,PATCH"

  # Health Checks
  HEALTH_CHECK_PATH: "/health"
  READINESS_CHECK_PATH: "/ready"